### ISSUE TITLE
Events are missing the target ip

### ISSUE THREAD

**Issue by dekelb** [Cymmetria/honeycomb#66]
The data that we send to the integrations (from the events) is missing the ip of the target machine (the ip that was attacked).
This is very important when we have multiple honeypots with multiple ips sending alerts to a single integration. It's impossible to know the machine that was targeted.

**Comment by omercnet** [comment]
The services were designed without attention to listening IP. If you’ll notice, we don’t ask for listening IP and default to `0.0.0.0`

Sending the destination IP that triggered the event is simple as passing it to the alert function

This can’t happen globally and would require change for all the the services since we provide freedom to the services over socket handling

How do you wanna handle this?

**Comment by dekelb** [comment]
So I guess we will need to change this in each service :(
We can probably close this one.
